# -*- coding: utf-8 -*-
"""Modelo_LSTM_TFM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zYRj2j7NpkLVZaMWtS5KJ5zycACLdTv
"""

# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsxqiK5GHUgnfSNuiABavqllGfCM-xP0
"""

"""
=============================================================
  TFM — Predicción de Ventas Diarias con LSTM
  Train : 2010-12-01 → 2011-11-08
  Test  : 2011-11-09 → 2011-12-09
=============================================================
Paleta Okabe-Ito (accesible para daltónicos):
  Azul      #0072B2
  Naranja   #E69F00
  Verde     #009E73
  Rojo/Verm #D55E00
  Lila      #CC79A7
  Cian      #56B4E9
  Amarillo  #F0E442
"""

# ── 0. Imports ────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import warnings
warnings.filterwarnings("ignore")

# ── Paleta Okabe-Ito ──────────────────────────────────────────────────────────
OI = {
    "blue":    "#0072B2",
    "orange":  "#E69F00",
    "green":   "#009E73",
    "red":     "#D55E00",
    "purple":  "#CC79A7",
    "cyan":    "#56B4E9",
    "yellow":  "#F0E442",
}

plt.rcParams.update({
    "figure.dpi":        150,
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.35,
    "legend.framealpha": 0.9,
})

# ── 1. Carga y agregación diaria ──────────────────────────────────────────────
print("▶ Cargando dataset …")
df_raw = pd.read_csv("dataset_clusterings_base.csv")
df_raw["fecha"] = pd.to_datetime(df_raw["fecha"])

daily = (
    df_raw.groupby("fecha")["importe_linea"]
          .sum()
          .reset_index()
          .rename(columns={"importe_linea": "beneficio_diario"})
          .sort_values("fecha")
)

# Rellenar posibles huecos de fin de semana / festivos con 0
full_idx  = pd.date_range(daily["fecha"].min(), daily["fecha"].max(), freq="D")
daily     = daily.set_index("fecha").reindex(full_idx, fill_value=0).reset_index()
daily.rename(columns={"index": "fecha"}, inplace=True)

print(f"   Rango  : {daily['fecha'].min().date()}  →  {daily['fecha'].max().date()}")
print(f"   Días   : {len(daily)}")

# ── 2. Split train / test ─────────────────────────────────────────────────────
TEST_START = pd.Timestamp("2011-11-09")

train = daily[daily["fecha"] <  TEST_START].copy()
test  = daily[daily["fecha"] >= TEST_START].copy()

print(f"\n   Train  : {len(train)} días  "
      f"({train['fecha'].min().date()} → {train['fecha'].max().date()})")
print(f"   Test   : {len(test)} días  "
      f"({test['fecha'].min().date()} → {test['fecha'].max().date()})")

# ── 3. Escalado ───────────────────────────────────────────────────────────────
scaler = MinMaxScaler(feature_range=(0, 1))
train_scaled = scaler.fit_transform(train[["beneficio_diario"]])
test_scaled  = scaler.transform(test[["beneficio_diario"]])

# ── 4. Construcción de ventanas temporales ────────────────────────────────────
LOOK_BACK = 30   # días de historia que ve el modelo

def create_sequences(data: np.ndarray, look_back: int):
    X, y = [], []
    for i in range(look_back, len(data)):
        X.append(data[i - look_back:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

X_train, y_train = create_sequences(train_scaled, LOOK_BACK)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)

# Para el test usamos los últimos LOOK_BACK días del train como contexto inicial
full_scaled = np.concatenate([train_scaled, test_scaled], axis=0)
X_test, y_test = create_sequences(full_scaled[-len(test_scaled) - LOOK_BACK:], LOOK_BACK)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

print(f"\n   X_train : {X_train.shape}   X_test : {X_test.shape}")

# ── 5. Arquitectura LSTM ──────────────────────────────────────────────────────
tf.random.set_seed(42)
np.random.seed(42)

model = Sequential([
    LSTM(128, return_sequences=True,  input_shape=(LOOK_BACK, 1)),
    Dropout(0.2),
    LSTM(64, return_sequences=False),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1),
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss="mse",
              metrics=["mae"])

model.summary()

# ── 6. Entrenamiento ──────────────────────────────────────────────────────────
callbacks = [
    EarlyStopping(monitor="val_loss", patience=20,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                      patience=10, min_lr=1e-6, verbose=1),
]

print("\n▶ Entrenando …")
history = model.fit(
    X_train, y_train,
    epochs         = 200,
    batch_size     = 16,
    validation_split = 0.15,
    callbacks      = callbacks,
    verbose        = 1,
)

# ── 7. Predicción y desnormalización ─────────────────────────────────────────
pred_scaled = model.predict(X_test)
pred        = scaler.inverse_transform(pred_scaled).flatten()
real        = scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()
dates_test  = test["fecha"].values[-len(real):]

# ── 8. Métricas ───────────────────────────────────────────────────────────────
mae  = mean_absolute_error(real, pred)
rmse = np.sqrt(mean_squared_error(real, pred))
r2   = r2_score(real, pred)
mape = np.mean(np.abs((real - pred) / np.where(real == 0, 1, real))) * 100

print("\n" + "="*45)
print("  RESULTADOS EN TEST")
print("="*45)
print(f"  MAE   : {mae:>12,.2f} €")
print(f"  RMSE  : {rmse:>12,.2f} €")
print(f"  MAPE  : {mape:>11.2f} %")
print(f"  R²    : {r2:>12.4f}")
print("="*45)

# ── 9. Gráficos ───────────────────────────────────────────────────────────────

# ─ 9a. Serie completa (train + test + predicción) ─────────────────────────────
fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(train["fecha"], train["beneficio_diario"],
        color=OI["blue"], linewidth=1.2, label="Train (real)")
ax.plot(test["fecha"].values[-len(real):], real,
        color=OI["orange"], linewidth=1.8, label="Test (real)")
ax.plot(test["fecha"].values[-len(pred):], pred,
        color=OI["red"], linewidth=1.8, linestyle="--", label="Predicción LSTM")

ax.axvline(TEST_START, color=OI["purple"], linestyle=":", linewidth=1.5,
           label="Inicio test (09-Nov-2011)")

ax.set_title("Predicción de Beneficios Diarios — LSTM", fontsize=14, pad=12)
ax.set_xlabel("Fecha")
ax.set_ylabel("Beneficio diario (€)")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
ax.xaxis.set_major_locator(mdates.MonthLocator())
fig.autofmt_xdate()
ax.legend()
fig.tight_layout()
fig.savefig("lstm_serie_completa.png")
print("\n▶ Guardado: lstm_serie_completa.png")

# ─ 9b. Zoom en el periodo test ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(12, 4))

ax.fill_between(dates_test, real, pred,
                alpha=0.15, color=OI["cyan"], label="Área de error")
ax.plot(dates_test, real,  color=OI["orange"], linewidth=2,
        marker="o", markersize=4, label="Real")
ax.plot(dates_test, pred,  color=OI["red"],    linewidth=2,
        linestyle="--", marker="s", markersize=4, label="Predicción LSTM")

ax.set_title("Detalle período test (09-Nov → 09-Dic 2011)", fontsize=13, pad=10)
ax.set_xlabel("Fecha")
ax.set_ylabel("Beneficio diario (€)")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%d-%b"))
ax.xaxis.set_major_locator(mdates.WeekdayLocator(byweekday=0))
fig.autofmt_xdate()
ax.legend()
fig.tight_layout()
fig.savefig("lstm_zoom_test.png")
print("▶ Guardado: lstm_zoom_test.png")

# ─ 9c. Real vs Predicho (scatter) ────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(5.5, 5.5))

ax.scatter(real, pred, color=OI["blue"], edgecolors="white",
           linewidth=0.5, s=60, alpha=0.85, zorder=3, label="Observaciones")

lim_min = min(real.min(), pred.min()) * 0.95
lim_max = max(real.max(), pred.max()) * 1.05
ax.plot([lim_min, lim_max], [lim_min, lim_max],
        color=OI["red"], linestyle="--", linewidth=1.5,
        label="Predicción perfecta", zorder=2)

ax.set_title(f"Real vs Predicho — R² = {r2:.3f}", fontsize=12, pad=10)
ax.set_xlabel("Beneficio real (€)")
ax.set_ylabel("Beneficio predicho (€)")
ax.set_xlim(lim_min, lim_max)
ax.set_ylim(lim_min, lim_max)
ax.set_aspect("equal")
ax.legend()
fig.tight_layout()
fig.savefig("lstm_scatter.png")
print("▶ Guardado: lstm_scatter.png")

# ─ 9d. Curvas de pérdida ──────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, metric, title in zip(
        axes,
        [("loss", "val_loss"), ("mae", "val_mae")],
        ["MSE Loss", "MAE"]):
    ax.plot(history.history[metric[0]],
            color=OI["blue"],   linewidth=1.5, label="Train")
    ax.plot(history.history[metric[1]],
            color=OI["orange"], linewidth=1.5, label="Validación",
            linestyle="--")
    ax.set_title(f"Curva de {title}", fontsize=12)
    ax.set_xlabel("Época")
    ax.set_ylabel(title)
    ax.legend()

fig.suptitle("Histórico de entrenamiento", fontsize=13, y=1.02)
fig.tight_layout()
fig.savefig("lstm_loss_curves.png", bbox_inches="tight")
print("▶ Guardado: lstm_loss_curves.png")

# ─ 9e. Residuos ───────────────────────────────────────────────────────────────
residuos = real - pred

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

# Residuo en el tiempo
axes[0].bar(range(len(residuos)), residuos,
            color=[OI["green"] if r >= 0 else OI["red"] for r in residuos],
            alpha=0.8, width=0.8)
axes[0].axhline(0, color="black", linewidth=0.8)
axes[0].set_title("Residuos en el tiempo", fontsize=12)
axes[0].set_xlabel("Día (test)")
axes[0].set_ylabel("Error (€)")

# Histograma de residuos
axes[1].hist(residuos, bins=12, color=OI["cyan"],
             edgecolor="white", linewidth=0.5, alpha=0.9)
axes[1].axvline(residuos.mean(), color=OI["red"], linewidth=1.5,
                linestyle="--", label=f"Media = {residuos.mean():,.0f} €")
axes[1].set_title("Distribución de residuos", fontsize=12)
axes[1].set_xlabel("Residuo (€)")
axes[1].set_ylabel("Frecuencia")
axes[1].legend()

fig.suptitle("Análisis de Residuos — Período Test", fontsize=13, y=1.02)
fig.tight_layout()
fig.savefig("lstm_residuos.png", bbox_inches="tight")
print("▶ Guardado: lstm_residuos.png")

plt.show()

# ── 10. Tabla de resultados ───────────────────────────────────────────────────
results_df = pd.DataFrame({
    "fecha":      pd.to_datetime(dates_test),
    "real":       np.round(real, 2),
    "prediccion": np.round(pred, 2),
    "error_abs":  np.round(np.abs(real - pred), 2),
    "error_rel_%": np.round(
        np.abs(real - pred) / np.where(real == 0, 1, real) * 100, 2),
})

print("\nResumen por día:\n")
print(results_df.to_string(index=False))