# -*- coding: utf-8 -*-
"""Regresion_PolinomicaTFM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158lTfQ28eMpf4AAC7tKf8gavbg67SNfm
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
REGRESIÓN POLINÓMICA PARA PREDICCIÓN DE VENTAS DIARIAS
Dataset: transacciones entre 2010-12-01 y 2011-12-09
Objetivo: Predecir ventas entre 2011-11-09 y 2011-12-09
Usando datos de entrenamiento: 2010-12-01 a 2011-11-08
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import json
from datetime import datetime

# Configurar estilos
sns.set_theme(style="whitegrid")
sns.set_palette("colorblind")
plt.rcParams['figure.figsize'] = (14, 7)
plt.rcParams['font.size'] = 10

print("=" * 90)
print("REGRESIÓN POLINÓMICA PARA PREDICCIÓN DE VENTAS DIARIAS")
print("=" * 90)

# ===== CARGAR Y EXPLORAR DATOS =====
print("\n📊 FASE 1: CARGANDO Y EXPLORANDO DATOS")
print("-" * 90)

df = pd.read_csv('dataset_clusterings_base (1).csv', encoding='ISO-8859-1')

print(f"✅ Dataset cargado: {len(df)} transacciones")
print(f"   Columnas: {df.shape[1]}")
print(f"   Fecha inicial: {df['fecha'].min()}")
print(f"   Fecha final: {df['fecha'].max()}")

# Explorar estructura
print(f"\n📋 Primeras filas del dataset:")
print(df[['numero_factura', 'fecha', 'cantidad', 'precio_unitario', 'importe_linea']].head())

# ===== PREPARACIÓN DE DATOS =====
print("\n\n📊 FASE 2: PREPARACIÓN DE DATOS")
print("-" * 90)



# Convertir fecha a datetime
df['fecha'] = pd.to_datetime(df['fecha'], dayfirst=True, errors='coerce')

# Limpiar valores monetarios si es necesario
# Verificar si importe_linea es string con comas
if isinstance(df['importe_linea'].iloc[0], str):
    df['importe_linea'] = df['importe_linea'].str.replace(',', '.').astype(float)
else:
    df['importe_linea'] = pd.to_numeric(df['importe_linea'], errors='coerce')

print(f"✅ Fechas convertidas a datetime")
print(f"✅ Importes numéricos: {df['importe_linea'].dtype}")

# Agrupar por día para obtener ventas diarias totales
daily_sales = df.groupby(df['fecha'].dt.date)['importe_linea'].sum().reset_index()
daily_sales.columns = ['Date', 'Revenue']
daily_sales['Date'] = pd.to_datetime(daily_sales['Date'])
daily_sales = daily_sales.sort_values('Date').reset_index(drop=True)

print(f"\n✅ Datos agregados por día: {len(daily_sales)} días únicos")
print(f"   Rango: {daily_sales['Date'].min().date()} a {daily_sales['Date'].max().date()}")
print(f"   Ventas diarias mín: ${daily_sales['Revenue'].min():.2f}")
print(f"   Ventas diarias máx: ${daily_sales['Revenue'].max():.2f}")
print(f"   Ventas diarias promedio: ${daily_sales['Revenue'].mean():.2f}")

# ===== DIVISIÓN TRAIN/TEST SEGÚN ENUNCIADO =====
print("\n\n📊 FASE 3: DIVISIÓN TRAIN/TEST SEGÚN ENUNCIADO")
print("-" * 90)

# Train: 2010-12-01 a 2011-11-08 (inclusive)
# Test: 2011-11-09 a 2011-12-09 (inclusive)

train_start = pd.to_datetime('2010-12-01')
train_end = pd.to_datetime('2011-11-08')
test_start = pd.to_datetime('2011-11-09')
test_end = pd.to_datetime('2011-12-09')

train = daily_sales[(daily_sales['Date'] >= train_start) &
                    (daily_sales['Date'] <= train_end)].copy()

test = daily_sales[(daily_sales['Date'] >= test_start) &
                   (daily_sales['Date'] <= test_end)].copy()

print(f"🔹 CONJUNTO DE ENTRENAMIENTO:")
print(f"   Período: {train['Date'].min().date()} a {train['Date'].max().date()}")
print(f"   Número de días: {len(train)}")
print(f"   Ingresos totales: ${train['Revenue'].sum():.2f}")
print(f"   Ingresos promedio: ${train['Revenue'].mean():.2f}")

print(f"\n🔹 CONJUNTO DE TEST:")
print(f"   Período: {test['Date'].min().date()} a {test['Date'].max().date()}")
print(f"   Número de días: {len(test)}")
print(f"   Ingresos totales: ${test['Revenue'].sum():.2f}")
print(f"   Ingresos promedio: ${test['Revenue'].mean():.2f}")

# Validación
assert len(train) > 0, "❌ Conjunto de entrenamiento vacío"
assert len(test) > 0, "❌ Conjunto de test vacío"

print(f"\n✅ Validación completada: ambos conjuntos con datos")

# ===== TRANSFORMACIÓN PARA REGRESIÓN POLINÓMICA =====
print("\n\n📊 FASE 4: TRANSFORMACIÓN PARA REGRESIÓN POLINÓMICA")
print("-" * 90)

# Convertir fechas a número de días desde el inicio del entrenamiento
train['Days'] = (train['Date'] - train['Date'].min()).dt.days
test['Days'] = (test['Date'] - train['Date'].min()).dt.days

print(f"✅ Fechas convertidas a días desde inicio del entrenamiento")
print(f"   Rango train: {train['Days'].min()} a {train['Days'].max()} días")
print(f"   Rango test: {test['Days'].min()} a {test['Days'].max()} días")

# Preparar características y objetivos
X_train = train[['Days']].values
y_train = train['Revenue'].values

X_test = test[['Days']].values
y_test = test['Revenue'].values

print(f"\n✅ Características preparadas:")
print(f"   X_train shape: {X_train.shape}")
print(f"   y_train shape: {y_train.shape}")
print(f"   X_test shape: {X_test.shape}")
print(f"   y_test shape: {y_test.shape}")

# ===== ENTRENAMIENTO DEL MODELO =====
print("\n\n🤖 FASE 5: ENTRENAMIENTO DEL MODELO")
print("-" * 90)

degree = 3
print(f"🔹 Configuración del modelo:")
print(f"   Algoritmo: Regresión Lineal (Mínimos Cuadrados Ordinarios)")
print(f"   Grado del polinomio: {degree}")
print(f"   Muestras de entrenamiento: {len(X_train)}")

# Crear polinomio
poly = PolynomialFeatures(degree=degree)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

print(f"\n✅ Características polinómicas creadas:")
print(f"   Número de características: {X_train_poly.shape[1]}")
print(f"   Orden: 1, x, x², x³")

# Entrenar modelo
model = LinearRegression()
model.fit(X_train_poly, y_train)

print(f"\n✅ Modelo entrenado exitosamente")

# Realizar predicciones
y_pred = model.predict(X_test_poly)

print(f"✅ Predicciones generadas para {len(y_pred)} días")

# ===== EVALUACIÓN DEL MODELO =====
print("\n\n📊 FASE 6: EVALUACIÓN DEL MODELO")
print("-" * 90)

# Calcular métricas
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

# Baseline naive (predicción = promedio de train)
y_baseline = np.full_like(y_test, y_train.mean(), dtype=float)
baseline_mae = mean_absolute_error(y_test, y_baseline)
baseline_rmse = np.sqrt(mean_squared_error(y_test, y_baseline))
baseline_r2 = r2_score(y_test, y_baseline)

print(f"\n🔹 MÉTRICAS DEL MODELO:")
print(f"   MAE (Error Absoluto Medio):           ${mae:>12.2f}")
print(f"   RMSE (Raíz del Error Cuadrático):    ${rmse:>12.2f}")
print(f"   R² (Coeficiente de Determinación):   {r2:>12.4f}")
print(f"   MAPE (Error Porcentual Absoluto):    {mape:>11.2f}%")

print(f"\n🔹 COMPARACIÓN CON BASELINE NAIVE:")
print(f"   Baseline MAE:                         ${baseline_mae:>12.2f}")
print(f"   Nuestro MAE:                          ${mae:>12.2f}")
mejora_mae = ((baseline_mae - mae) / baseline_mae) * 100
print(f"   Mejora:                               {mejora_mae:>11.2f}%")

# Estadísticas de error
errors = y_test - y_pred
print(f"\n🔹 ESTADÍSTICAS DE ERROR:")
print(f"   Media del error:                      ${errors.mean():>12.2f}")
print(f"   Mediana del error:                    ${np.median(errors):>12.2f}")
print(f"   Desviación típica del error:          ${errors.std():>12.2f}")
print(f"   Error máximo (absoluto):              ${np.abs(errors).max():>12.2f}")
print(f"   Error mínimo (absoluto):              ${np.abs(errors).min():>12.2f}")

# ===== COEFICIENTES DEL MODELO =====
print("\n\n📊 FASE 7: COEFICIENTES DEL MODELO")
print("-" * 90)

print(f"\n🔹 ECUACIÓN DEL POLINOMIO:")
print(f"   Intercepción (b₀): {model.intercept_:.6f}")
print(f"   Coeficiente x (b₁): {model.coef_[1]:.6e}")
print(f"   Coeficiente x² (b₂): {model.coef_[2]:.6e}")
print(f"   Coeficiente x³ (b₃): {model.coef_[3]:.6e}")

print(f"\n✅ PREDICCIÓN = {model.intercept_:.2f} + {model.coef_[1]:.6e}·x + {model.coef_[2]:.6e}·x² + {model.coef_[3]:.6e}·x³")




# ===== GRÁFICOS =====
print("\n\n📊 FASE 8: GENERANDO VISUALIZACIONES")
print("-" * 90)

# Crear figura con múltiples gráficos
fig = plt.figure(figsize=(16, 12))

# --------- GRÁFICO 1: SERIE TEMPORAL COMPLETA ---------
ax1 = plt.subplot(2, 3, 1)
ax1.plot(train['Date'], y_train, label='Entrenamiento', linewidth=2, color='#1f77b4', marker='o', markersize=3)
ax1.plot(test['Date'], y_test, label='Real (Test)', linewidth=2.5, color='#2ca02c', marker='s', markersize=4)
ax1.plot(test['Date'], y_pred, label='Predicción', linestyle='--', linewidth=2.5, color='#ff7f0e', marker='^', markersize=4)
ax1.axvline(x=pd.to_datetime('2011-11-08'), color='red', linestyle=':', linewidth=2, alpha=0.7, label='Separación Train/Test')
ax1.set_title('Predicción de Ventas Diarias\n(Serie Temporal Completa)', fontsize=12, fontweight='bold')
ax1.set_xlabel('Fecha', fontsize=10)
ax1.set_ylabel('Ingresos ($)', fontsize=10)
ax1.legend(fontsize=9, loc='upper left')
ax1.grid(True, alpha=0.3)
plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45)

# --------- GRÁFICO 2: ERRORES ABSOLUTOS POR DÍA ---------
ax2 = plt.subplot(2, 3, 2)
ax2.plot(test['Date'], errors, marker='o', linewidth=1.5, markersize=6, color='#1f77b4', label='Error absoluto')
ax2.axhline(0, linestyle='--', color='red', linewidth=2, label='Error = 0')
ax2.axhline(errors.mean(), linestyle='--', color='orange', linewidth=1.5, label=f'Media: ${errors.mean():.2f}')
ax2.fill_between(test['Date'], errors.mean() - errors.std(), errors.mean() + errors.std(), alpha=0.2, color='blue', label='±1σ')
ax2.set_title('Análisis de Errores por Día', fontsize=12, fontweight='bold')
ax2.set_xlabel('Fecha', fontsize=10)
ax2.set_ylabel('Error ($)', fontsize=10)
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3)
plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45)

# --------- GRÁFICO 3: AJUSTE DEL MODELO ---------
ax3 = plt.subplot(2, 3, 3)
ax3.scatter(train['Days'], y_train, alpha=0.5, s=40, label='Datos de entrenamiento', color='#1f77b4')
x_range = np.linspace(train['Days'].min(), test['Days'].max(), 300).reshape(-1, 1)
x_range_poly = poly.transform(x_range)
y_range_pred = model.predict(x_range_poly)
ax3.plot(x_range, y_range_pred, label='Ajuste polinómico (grado 3)', linewidth=2.5, color='#d62728')
ax3.set_title('Ajuste del Modelo Polinómico', fontsize=12, fontweight='bold')
ax3.set_xlabel('Días desde inicio', fontsize=10)
ax3.set_ylabel('Ingresos ($)', fontsize=10)
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3)

# --------- GRÁFICO 4: ERROR PORCENTUAL ---------
ax4 = plt.subplot(2, 3, 4)
error_pct = (y_test - y_pred) / y_test * 100
ax4.plot(test['Date'], error_pct, marker='o', linewidth=1.5, markersize=6, color='#2ca02c')
ax4.axhline(0, linestyle='--', color='red', linewidth=2)
ax4.axhline(error_pct.mean(), linestyle='--', color='orange', linewidth=1.5, label=f'Media: {error_pct.mean():.2f}%')
ax4.set_title('Error Porcentual por Día', fontsize=12, fontweight='bold')
ax4.set_xlabel('Fecha', fontsize=10)
ax4.set_ylabel('Error (%)', fontsize=10)
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3)
plt.setp(ax4.xaxis.get_majorticklabels(), rotation=45)

# --------- GRÁFICO 5: DISTRIBUCIÓN DE ERRORES ---------
ax5 = plt.subplot(2, 3, 5)
ax5.hist(errors, bins=12, alpha=0.7, color='#1f77b4', edgecolor='black', density=True)
ax5.axvline(errors.mean(), color='red', linestyle='--', linewidth=2, label=f'Media: ${errors.mean():.2f}')
ax5.axvline(np.median(errors), color='green', linestyle='--', linewidth=2, label=f'Mediana: ${np.median(errors):.2f}')
# Añadir KDE
from scipy import stats
kde = stats.gaussian_kde(errors)
x_kde = np.linspace(errors.min(), errors.max(), 100)
ax5.plot(x_kde, kde(x_kde), 'k-', linewidth=2, label='KDE')
ax5.set_title('Distribución de Errores', fontsize=12, fontweight='bold')
ax5.set_xlabel('Error ($)', fontsize=10)
ax5.set_ylabel('Densidad', fontsize=10)
ax5.legend(fontsize=9)
ax5.grid(True, alpha=0.3, axis='y')

# --------- GRÁFICO 6: REAL VS PREDICCIÓN (SCATTER) ---------
ax6 = plt.subplot(2, 3, 6)
ax6.scatter(y_test, y_pred, alpha=0.6, s=80, color='#1f77b4', edgecolors='black', linewidth=0.5)
min_val = min(y_test.min(), y_pred.min())
max_val = max(y_test.max(), y_pred.max())
ax6.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2.5, label='Predicción Perfecta')
ax6.set_title('Correlación: Real vs Predicción', fontsize=12, fontweight='bold')
ax6.set_xlabel('Ventas Reales ($)', fontsize=10)
ax6.set_ylabel('Ventas Predichas ($)', fontsize=10)
ax6.legend(fontsize=9)
ax6.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()  # <--- CAMBIADO: Ahora se muestra el gráfico combinado

# --- Gráficos individuales por separado ---

# Gráfico 1
fig1, ax1 = plt.subplots(figsize=(14, 7))
ax1.plot(train['Date'], y_train, label='Entrenamiento', linewidth=2, color='#1f77b4', marker='o', markersize=3)
ax1.plot(test['Date'], y_test, label='Real (Test)', linewidth=2.5, color='#2ca02c', marker='s', markersize=4)
ax1.plot(test['Date'], y_pred, label='Predicción', linestyle='--', linewidth=2.5, color='#ff7f0e', marker='^', markersize=4)
ax1.axvline(x=pd.to_datetime('2011-11-08'), color='red', linestyle=':', linewidth=2, alpha=0.7)
ax1.set_title('Predicción de Ventas Diarias (Regresión Polinómica Grado 3)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Fecha', fontsize=11)
ax1.set_ylabel('Ingresos ($)', fontsize=11)
ax1.legend(fontsize=11)
ax1.grid(True, alpha=0.3)
plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45)
plt.tight_layout()
plt.show()  # <--- CAMBIADO

# Gráfico 2
fig2, ax2 = plt.subplots(figsize=(14, 7))
ax2.plot(test['Date'], errors, marker='o', linewidth=1.5, markersize=6, color='#1f77b4')
ax2.axhline(0, linestyle='--', color='red', linewidth=2)
ax2.axhline(errors.mean(), linestyle='--', color='orange', linewidth=1.5, label=f'Media: ${errors.mean():.2f}')
ax2.fill_between(test['Date'], errors.mean() - errors.std(), errors.mean() + errors.std(), alpha=0.2, color='blue')
ax2.set_title('Análisis de Errores de Predicción por Día', fontsize=14, fontweight='bold')
ax2.set_xlabel('Fecha', fontsize=11)
ax2.set_ylabel('Error ($)', fontsize=11)
ax2.legend(fontsize=11)
ax2.grid(True, alpha=0.3)
plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45)
plt.tight_layout()
plt.show()  # <--- CAMBIADO

# Gráfico 3
fig3, ax3 = plt.subplots(figsize=(14, 7))
ax3.scatter(train['Days'], y_train, alpha=0.5, s=40, label='Datos de entrenamiento', color='#1f77b4')
ax3.plot(x_range, y_range_pred, label='Ajuste polinómico (grado 3)', linewidth=2.5, color='#d62728')
ax3.set_title('Ajuste del Modelo Polinómico a los Datos de Entrenamiento', fontsize=14, fontweight='bold')
ax3.set_xlabel('Días desde el inicio del entrenamiento', fontsize=11)
ax3.set_ylabel('Ingresos ($)', fontsize=11)
ax3.legend(fontsize=11)
ax3.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()  # <--- CAMBIADO

# Gráfico 6 (Scatter final)
fig6, ax6 = plt.subplots(figsize=(10, 8))
ax6.scatter(y_test, y_pred, alpha=0.6, s=80, color='#1f77b4', edgecolors='black', linewidth=0.5)
ax6.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2.5, label='Predicción Perfecta')
ax6.set_title('Correlación: Ventas Reales vs Predichas', fontsize=14, fontweight='bold')
ax6.set_xlabel('Ventas Reales ($)', fontsize=11)
ax6.set_ylabel('Ventas Predichas ($)', fontsize=11)
ax6.legend(fontsize=11)
ax6.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()  # <--- CAMBIADO

# ===== MOSTRAR PREDICCIONES =====
print("\n\n📊 FASE 9: RESULTADOS DE PREDICCIÓN")
print("-" * 90)

predictions_df = pd.DataFrame({
    'Fecha': test['Date'],
    'Ventas_Reales': y_test,
    'Ventas_Predichas': y_pred,
    'Error_Absoluto': errors,
    'Error_Porcentual_%': (errors / y_test) * 100
})

print(f"\n📋 Primeras 5 predicciones:")
print(predictions_df.head())

print("\n" + "=" * 90)
print("✅ ANÁLISIS COMPLETADO Y MOSTRADO EN PANTALLA")
print("=" * 90)





