# -*- coding: utf-8 -*-
"""DBSCAN_FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7nNJ0tXC9y7J1fhuLRKd6k4DO5cGixh
"""

# -*- coding: utf-8 -*-
"""
DBSCAN MEJORADO
Dataset: dataset_clientes_clustering.csv


"""

# ──────────────────────────────────────────────────────────────────────────────
# 1. IMPORTACIONES
# ──────────────────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import (
    silhouette_score, silhouette_samples,
    davies_bouldin_score, calinski_harabasz_score
)
from sklearn.covariance import EllipticEnvelope
from scipy.spatial.distance import pdist, squareform
import warnings

warnings.filterwarnings("ignore")

# Estilo visual
sns.set_theme(style="whitegrid", palette="husl")
plt.rcParams["figure.dpi"] = 120

print("=" * 80)
print("DBSCAN MEJORADO - Clustering de Clientes con Búsqueda Inteligente de Parámetros")
print("=" * 80)

# ──────────────────────────────────────────────────────────────────────────────
# 2. CARGA Y PREPROCESAMIENTO
# ──────────────────────────────────────────────────────────────────────────────
print("\n[1/8] Cargando datos...")
df = pd.read_csv("dataset_clientes_clustering.csv")
print(f"✓ Dataset cargado: {df.shape[0]} clientes, {df.shape[1]} columnas")

# Selección de features (igual que en HDBSCAN)
columnas_usar = [
    "total_compras",
    "valor_total_compras",
    "valor_medio_por_compra",
    "frecuencia_compra",
    "dias_como_cliente",
    "cantidad_total_productos",
    "porcentaje_compras_fines_semana",
    "meses_activo",
    "valor_mensual_medio"
]

df_feat = df[columnas_usar].copy()

# Rellenar NaN
for col in df_feat.columns:
    if df_feat[col].isnull().sum() > 0:
        df_feat[col].fillna(df_feat[col].median(), inplace=True)

print(f"✓ Features seleccionadas: {len(columnas_usar)}")
print(f"\nEstadísticas básicas:")
print(df_feat.describe().round(2))

# ──────────────────────────────────────────────────────────────────────────────
# 3. ESCALADO ROBUSTO (Mejora 1: RobustScaler en lugar de StandardScaler)
# ──────────────────────────────────────────────────────────────────────────────
print("\n[2/8] Aplicando escalado robusto...")
scaler = RobustScaler()
X_scaled = scaler.fit_transform(df_feat)
print(f"✓ Escalado completado (RobustScaler)")

# ──────────────────────────────────────────────────────────────────────────────
# 4. ELIMINACIÓN DE OUTLIERS (Mejora 2: EllipticEnvelope como en DBSCAN original)
# ──────────────────────────────────────────────────────────────────────────────
print("\n[3/8] Detectando y eliminando outliers...")
detector = EllipticEnvelope(contamination=0.10, random_state=42, support_fraction=0.9)
mask_inliers = detector.fit_predict(X_scaled) == 1

X_clean = X_scaled[mask_inliers]
df_clean = df[mask_inliers].copy().reset_index(drop=True)

print(f"✓ Outliers eliminados: {(~mask_inliers).sum()} ({100*(~mask_inliers).sum()/len(mask_inliers):.1f}%)")
print(f"  Clientes restantes: {X_clean.shape[0]}")

# ──────────────────────────────────────────────────────────────────────────────
# 5. PCA REDUCIDO (Mejora 3: 3 componentes como en DBSCAN original)
# ──────────────────────────────────────────────────────────────────────────────
print("\n[4/8] Aplicando PCA...")
N_COMPONENTES_PCA = 3
pca = PCA(n_components=N_COMPONENTES_PCA, random_state=42)
X_pca = pca.fit_transform(X_clean)

var_acum = 100 * sum(pca.explained_variance_ratio_)
print(f"✓ PCA con {N_COMPONENTES_PCA} componentes")
print(f"  Varianza explicada: {var_acum:.1f}%")
for i, v in enumerate(pca.explained_variance_ratio_):
    print(f"    PC{i+1}: {100*v:.1f}%")

# ──────────────────────────────────────────────────────────────────────────────
# 6. BÚSQUEDA INTELIGENTE DE PARÁMETROS (Mejora 4: Similar a HDBSCAN)
# ──────────────────────────────────────────────────────────────────────────────
print("\n[5/8] Buscando parámetros óptimos...")

# Calcular rango dinámico de eps basado en percentiles
# (Similar a HDBSCAN pero usando DBSCAN)
def calcular_rango_eps(X, min_samples_ref=5):
    """Calcula rango de eps basado en distancias reales del dataset"""
    nbrs = NearestNeighbors(n_neighbors=min_samples_ref).fit(X)
    distancias, _ = nbrs.kneighbors(X)
    distancias_k = distancias[:, min_samples_ref - 1]

    eps_min = float(np.percentile(distancias_k, 10))
    eps_max = float(np.percentile(distancias_k, 70))

    return eps_min, eps_max, distancias_k

eps_min, eps_max, distancias_k = calcular_rango_eps(X_pca)
print(f"✓ Rango de eps calculado: {eps_min:.4f} → {eps_max:.4f}")

# Mejora 5: Búsqueda exhaustiva como en HDBSCAN
# Generamos más valores de eps (similar a los 28 parámetros de HDBSCAN)
eps_values = np.linspace(eps_min, eps_max, 20)
min_samples_values = [3, 5, 8, 10, 15]  # Similar a HDBSCAN

total_combos = len(eps_values) * len(min_samples_values)
print(f"✓ Explorando {total_combos} combinaciones (eps={len(eps_values)}, min_samples={len(min_samples_values)})")

# Función de evaluación mejorada
def evaluar_dbscan_mejorado(X, eps_vals, ms_vals):
    """
    Evalúa combinaciones de DBSCAN con múltiples métricas
    Similar a find_optimal_parameters de HDBSCAN
    """
    resultados = []

    for eps in eps_vals:
        for ms in ms_vals:
            # Aplicar DBSCAN
            dbscan = DBSCAN(eps=eps, min_samples=ms)
            labels = dbscan.fit_predict(X)

            # Contar clusters y ruido
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
            n_ruido = int(np.sum(labels == -1))
            pct_ruido = 100 * n_ruido / len(labels)

            # Filtros iniciales (similar a HDBSCAN)
            if n_clusters < 2 or n_clusters > 8:
                continue
            if pct_ruido > 50:  # Relajado: HDBSCAN usa 30%, pero damos más margen a DBSCAN
                continue

            # Validar que hay suficientes puntos no-ruido
            mask_no_ruido = labels != -1
            if np.sum(mask_no_ruido) <= n_clusters:
                continue

            # Equilibrio de clusters
            tamaños_clusters = []
            for cluster_id in set(labels):
                if cluster_id != -1:
                    tamaños_clusters.append(np.sum(labels == cluster_id))

            if tamaños_clusters:
                equilibrio = np.std(tamaños_clusters) / (np.mean(tamaños_clusters) + 1e-9)
                pct_mayor = 100 * max(tamaños_clusters) / np.sum(mask_no_ruido)

                # Rechazar si un cluster domina (igual que HDBSCAN)
                if pct_mayor > 80:
                    continue
            else:
                equilibrio = float('inf')
                pct_mayor = 100.0

            # Calcular métricas de calidad
            try:
                sil = silhouette_score(X[mask_no_ruido], labels[mask_no_ruido])
                db = davies_bouldin_score(X[mask_no_ruido], labels[mask_no_ruido])
                ch = calinski_harabasz_score(X[mask_no_ruido], labels[mask_no_ruido])
            except:
                continue

            resultados.append({
                'eps': round(eps, 4),
                'min_samples': ms,
                'n_clusters': n_clusters,
                'n_ruido': n_ruido,
                'pct_ruido': round(pct_ruido, 1),
                'pct_mayor': round(pct_mayor, 1),
                'equilibrio': round(equilibrio, 4),
                'silhouette': round(sil, 4),
                'davies_bouldin': round(db, 4),
                'calinski_harabasz': round(ch, 4)
            })

    return resultados

# Ejecutar búsqueda
resultados = evaluar_dbscan_mejorado(X_pca, eps_values, min_samples_values)

if not resultados:
    raise RuntimeError(
        "No se encontró ninguna combinación válida con DBSCAN.\n"
        "Intenta aumentar los límites de ruido o usar HDBSCAN."
    )

df_resultados = pd.DataFrame(resultados)
print(f"✓ Se encontraron {len(df_resultados)} combinaciones válidas")

# ──────────────────────────────────────────────────────────────────────────────
# 7. PUNTUACIÓN PONDERADA (Mejora 6: Similar a HDBSCAN)
# ──────────────────────────────────────────────────────────────────────────────

def normalizar(series):
    """Normaliza a rango [0, 1]"""
    min_val = series.min()
    max_val = series.max()
    if max_val - min_val < 1e-9:
        return pd.Series(np.ones(len(series)), index=series.index)
    return (series - min_val) / (max_val - min_val)

# Puntuación similar a HDBSCAN
df_resultados['score_final'] = (
    normalizar(df_resultados['silhouette']) * 0.30 +  # Silueta
    (1 - normalizar(df_resultados['davies_bouldin'])) * 0.20 +  # Davies-Bouldin (invertido)
    normalizar(df_resultados['calinski_harabasz']) * 0.20 +  # Calinski-Harabasz
    (1 - normalizar(df_resultados['equilibrio'])) * 0.20 +  # Equilibrio (invertido)
    (1 - normalizar(df_resultados['pct_ruido'])) * 0.10  # Porcentaje ruido (invertido)
)

df_resultados = df_resultados.sort_values('score_final', ascending=False).reset_index(drop=True)

# Mostrar TOP 10
print(f"\n🏆 TOP 10 CONFIGURACIONES:")
cols_show = ['eps', 'min_samples', 'n_clusters', 'pct_ruido', 'silhouette', 'davies_bouldin', 'score_final']
print(df_resultados[cols_show].head(10).to_string(index=False))

# Mejor configuración
mejor_config = df_resultados.iloc[0]
EPS_OPTIMO = mejor_config['eps']
MIN_SAMPLES_OPTIMO = int(mejor_config['min_samples'])

print(f"\n✨ CONFIGURACIÓN ÓPTIMA SELECCIONADA:")
print(f"   eps = {EPS_OPTIMO}")
print(f"   min_samples = {MIN_SAMPLES_OPTIMO}")
print(f"   Clusters esperados: {int(mejor_config['n_clusters'])}")
print(f"   Ruido esperado: {mejor_config['pct_ruido']:.1f}%")
print(f"   Silueta: {mejor_config['silhouette']:.4f}")
print(f"   Score final: {mejor_config['score_final']:.4f}")

# ──────────────────────────────────────────────────────────────────────────────
# 8. APLICAR DBSCAN CON PARÁMETROS ÓPTIMOS
# ──────────────────────────────────────────────────────────────────────────────
print("\n[6/8] Aplicando DBSCAN con parámetros óptimos...")

dbscan_final = DBSCAN(eps=EPS_OPTIMO, min_samples=MIN_SAMPLES_OPTIMO)
labels = dbscan_final.fit_predict(X_pca)

# Estadísticas
n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = int(np.sum(labels == -1))
mask_no_ruido = labels != -1

print(f"✓ Clusters encontrados: {n_clusters}")
print(f"  Puntos de ruido: {n_ruido} ({100*n_ruido/len(labels):.1f}%)")
print(f"  Puntos asignados: {np.sum(mask_no_ruido)}")

# Métricas de calidad
if np.sum(mask_no_ruido) > n_clusters:
    sil_score = silhouette_score(X_pca[mask_no_ruido], labels[mask_no_ruido])
    db_score = davies_bouldin_score(X_pca[mask_no_ruido], labels[mask_no_ruido])
    ch_score = calinski_harabasz_score(X_pca[mask_no_ruido], labels[mask_no_ruido])

    print(f"\n📊 MÉTRICAS DE CALIDAD:")
    print(f"  Silueta: {sil_score:.4f} {'✓' if sil_score > 0.4 else '⚠'}")
    print(f"  Davies-Bouldin: {db_score:.4f} {'✓' if db_score < 1.5 else '⚠'}")
    print(f"  Calinski-Harabasz: {ch_score:.2f}")

# ──────────────────────────────────────────────────────────────────────────────
# 9. VISUALIZACIONES
# ──────────────────────────────────────────────────────────────────────────────
print("\n[7/8] Generando visualizaciones...")

# 9.1 - Gráfico k-distancias
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# K-distancias
distancias_sort = np.sort(distancias_k)[::-1]
axes[0].plot(distancias_sort, linewidth=1.5, color="steelblue")
axes[0].axhline(y=EPS_OPTIMO, color="red", linestyle="--", linewidth=2, label=f"eps = {EPS_OPTIMO:.4f}")
axes[0].set_xlabel("Puntos ordenados por distancia decreciente")
axes[0].set_ylabel("Distancia al k-vecino")
axes[0].set_title("Gráfico k-distancias — eps detectado automáticamente")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Scatter 2D PCA
scatter = axes[1].scatter(X_pca[:, 0], X_pca[:, 1], c=labels, cmap='tab10',
                          alpha=0.6, s=30, edgecolors='black', linewidth=0.5)
axes[1].set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
axes[1].set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
axes[1].set_title("Clustering en espacio PCA 2D")
plt.colorbar(scatter, ax=axes[1], label='Cluster')

plt.tight_layout()
plt.savefig("dbscan_mejorado_parametros.png", dpi=300, bbox_inches='tight')
plt.show()

# 9.2 - Scatter 3D PCA
fig = plt.figure(figsize=(12, 5))

# 3D
ax1 = fig.add_subplot(121, projection='3d')
scatter_3d = ax1.scatter(X_pca[:, 0], X_pca[:, 1], X_pca[:, 2],
                         c=labels, cmap='tab10', alpha=0.6, s=20, edgecolors='black', linewidth=0.5)
ax1.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
ax1.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
ax1.set_zlabel(f"PC3 ({pca.explained_variance_ratio_[2]*100:.1f}%)")
ax1.set_title("Clustering en espacio PCA 3D")

# Distribución de tamaños
ax2 = fig.add_subplot(122)
conteo = []
for c in sorted(set(labels)):
    if c != -1:
        conteo.append({'cluster': c, 'n_clientes': np.sum(labels == c)})
conteo_df = pd.DataFrame(conteo)

if not conteo_df.empty:
    ax2.bar(conteo_df['cluster'].astype(str), conteo_df['n_clientes'], color='steelblue', alpha=0.8)
    ax2.set_xlabel("Cluster")
    ax2.set_ylabel("Nº clientes")
    ax2.set_title("Distribución de tamaño de clusters")
    ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig("dbscan_mejorado_3d.png", dpi=300, bbox_inches='tight')
plt.show()

# 9.3 - Silhouette Analysis
if np.sum(mask_no_ruido) > n_clusters:
    fig, ax = plt.subplots(figsize=(10, 6))

    silhouette_vals = silhouette_samples(X_pca[mask_no_ruido], labels[mask_no_ruido])
    y_lower = 10

    for i in sorted(set(labels[mask_no_ruido])):
        cluster_silhouette_vals = silhouette_vals[labels[mask_no_ruido] == i]
        cluster_silhouette_vals.sort()

        size_cluster_i = cluster_silhouette_vals.shape[0]
        y_upper = y_lower + size_cluster_i

        color = cm.tab10(i % 10)
        ax.fill_betweenx(np.arange(y_lower, y_upper),
                        0, cluster_silhouette_vals,
                        facecolor=color, edgecolor=color, alpha=0.7)

        ax.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))
        y_lower = y_upper + 10

    ax.set_xlabel("Silhouette Coefficient")
    ax.set_ylabel("Cluster")
    ax.axvline(x=sil_score, color="red", linestyle="--", label=f"Media: {sil_score:.3f}")
    ax.set_title("Silhouette Analysis — DBSCAN Mejorado")
    ax.legend()
    ax.set_yticks([])

    plt.tight_layout()
    plt.savefig("dbscan_mejorado_silhouette.png", dpi=300, bbox_inches='tight')
    plt.show()

# 9.4 - Heatmap de perfiles
print("\nAnalizando perfiles por cluster...")

df_con_cluster = df_clean.copy()
df_con_cluster['cluster'] = labels

vars_perfil = [
    'total_compras', 'valor_total_compras', 'valor_medio_por_compra',
    'frecuencia_compra', 'dias_como_cliente', 'diversidad_categorias',
    'porcentaje_compras_fines_semana', 'meses_activo', 'valor_mensual_medio',
    'cantidad_total_productos'
]

vars_disponibles = [v for v in vars_perfil if v in df_con_cluster.columns]

df_sin_ruido = df_con_cluster[df_con_cluster['cluster'] != -1]

if len(df_sin_ruido) > 0:
    perfil = df_sin_ruido.groupby("cluster")[vars_disponibles].mean().round(2)
    perfil_norm = (perfil - perfil.mean()) / (perfil.std() + 1e-9)

    fig, ax = plt.subplots(figsize=(14, 6))
    sns.heatmap(perfil_norm.T, annot=perfil.T.values, fmt=".1f",
                cmap="RdYlGn", linewidths=0.5, linecolor="white",
                cbar_kws={"label": "Z-score"}, ax=ax)
    ax.set_title("Heatmap de Perfiles por Cluster — DBSCAN Mejorado\n(colores = z-score; números = media real)")
    ax.set_xlabel("Cluster")
    ax.set_ylabel("Variable")

    plt.tight_layout()
    plt.savefig("dbscan_mejorado_perfiles.png", dpi=300, bbox_inches='tight')
    plt.show()

    print("\n📋 PERFIL MEDIO POR CLUSTER:")
    print(perfil.T.to_string())

# ──────────────────────────────────────────────────────────────────────────────
# 10. EXPORTAR RESULTADOS
# ──────────────────────────────────────────────────────────────────────────────
print("\n[8/8] Exportando resultados...")

df_con_cluster.to_csv("clientes_clustering_dbscan_mejorado.csv", index=False)
df_resultados.to_csv("parametros_dbscan_mejorado.csv", index=False)

print(f"✓ Archivo con clusters: clientes_clustering_dbscan_mejorado.csv")
print(f"✓ Archivo de parámetros: parametros_dbscan_mejorado.csv")

# ──────────────────────────────────────────────────────────────────────────────
# 11. RESUMEN FINAL
# ──────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 80)
print("RESUMEN FINAL — DBSCAN MEJORADO")
print("=" * 80)
print(f"""
📊 CONFIGURACIÓN FINAL:
   eps = {EPS_OPTIMO}
   min_samples = {MIN_SAMPLES_OPTIMO}

🎯 RESULTADOS:
   Clusters encontrados: {n_clusters}
   Puntos de ruido: {n_ruido} ({100*n_ruido/len(labels):.1f}%)
   Puntos asignados: {np.sum(mask_no_ruido)}

💡 NOTAS:
   - Si el ruido es muy alto (>20%), considerar aumentar el rango de eps
   - Si los clusters son desbalanceados, revisar los criterios de equilibrio
   - Para densidades muy variables, HDBSCAN sigue siendo superior
""")

print("=" * 80)
print("✓ Análisis completado exitosamente")
print("=" * 80)